### ISSUE TITLE
Note install command

### ISSUE THREAD

**Issue by ThSGM** [ute/mathjax3eqno#2]
Note that to install this, users may have to do this:

`quarto add ute/mathjax3eqno@master`

Took me a while to figure this out via this comment: https://stackoverflow.com/questions/76614176/cant-use-install-a-quarto-extension-created-by-myself-from-github

**Comment by ute** [comment]
Thank you very much for pointing that out, @ThSGM ! I did not have that problem earlier (with quarto 1.3), but now experienced it with another one of my extensions. Solved it by renaming the branch to `main`. Does it work for you now, with the original install code? Which quarto version are you using?

**Comment by ute** [comment]
Renaming the branch fixed ri :-)
